      - name: Install Dependencies
        run: npm install

      - name: Fix Cypress Binary Permissions
        run: |
          chmod +x $(npm bin)/cypress
          chmod +x ./node_modules/.bin/cypress
          chmod +x ./node_modules/cypress/bin/cypress

      - name: Start PHP Server
        run: php -S localhost:8000 > /dev/null 2>&1 &

      - name: Run Cypress
        run: ./node_modules/.bin/cypress run